version: '3'

services:
  db:
    build:
      context: ./db/
    image: emanoelmendes/mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/:/var/lib/mysql/
    ports:
      - 3306:3306
    networks:
      - nodenet

  webapp:
    build:
      context: ./node/
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node .
    depends_on: 
      - db
    volumes: 
      - ./node/:/app/
    networks:
      - nodenet

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    networks:
      - nodenet
    depends_on: 
      - webapp
    ports:
      - 8080:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/

networks:
  nodenet:
    driver: bridge
